#!/bin/bash
echo "file name: $0"
echo "first argument: $1"
echo "second argument: $2"
echo "quoted values: $@"
echo "quoted values: $*"
echo "number of arguments: $#"
echo "process id: $$"
echo "exit status of last command: $?"
echo "home directory: $HOME"
echo "current working directory: $PWD"
echo "shell name: $SHELL"
echo "user name: $USER"
echo "current date and time: $(date)"   
echo "process number: $!"